### ISSUE TITLE
Replacing LRIs

### ISSUE THREAD

**Issue by olbeimarton** [jcolinge/BulkSignalR#10]
Good afternoon,

I recently stumbled upon the BulkSignalR package, and find it very interesting, I would like to use it in my work. In the last paragraph of the paper the authors mention the possibility of modifying the LRI-s: 
"users can add to or replace the list of putative LRIs entirely opening the door to testing new LRIs."

Where are these sets stored in the package, how does one replace, let's say, Gene Ontology with another kind of relevant ontology? If I understand correctly, these are essentially gene sets that contain one or more receptors the active ligands can act upon, and thus there are data sources that could be fit for this purpose.

Best wishes,
Marton

**Comment by ZheFrench** [comment]
Dear Marton,

First of all, thank you very much for you interest in BSR.

As you already noticed, you can change the Ligand-Receptor set of interactions.
You have to provide your own dataframe of L-R pairs.
To do this , you first need to use the following function before calling other functions of BulkSignalR  :

`resetLRdb(db=data.frame(ligand=c("L1","L2"),receptor=c("R1","R2"), switch=TRUE)
`  

Note setting `switch to FALSE` will add your interactions to our core set of LR  whereas `switch=TRUE `will change the whole LRI with what you provide.

Thanks for letting us know.

Best,
Jean-Philippe

**Comment by ManarRashad** [comment]
@ZheFrench Thank you for your answer regarding this part and thanks also for this interesting package.
I have a question related to resetLRdb function, if I have a data frame contains 2 columns the first is ligand and the second is receptor, but the contents of the ligand is 1 value like "TGFB1" and the contents of the receptor are multimeric receptors for example: ACVR1B_TGFbR2

Should I change in the calculation of the z-score in the signature step or should I do something else ?

How can I adjust that?

Thanks in advance

**Comment by ZheFrench** [comment]
You should do something more like this : 

<table>
<tr>
 <td>ligand 
 <td>receptor 
<tr>
 <td>TGFB1 
 <td>ACVR1B 
<tr>
 <td>TGFB1 
 <td>TGFbR2 
</table>

Then if one of the receptors is connected to other gene targets in the internal network, it should work.
You don't have to change anything else.

**Comment by ManarRashad** [comment]
@ZheFrench thank you so much
