### ISSUE TITLE
I have trouble in differential analysis

### ISSUE THREAD

**Issue by Derricca** [jcolinge/BulkSignalR#12]
Hello, 

I'm thrilled to apply BulkSignalR package to my reseach. 
While I was trying 'differential mode' example in manual (http://127.0.0.1:20402/library/BulkSignalR/doc/BulkSignalR-Differential.html), 

I got an error in function 'defineClusterComp', and the error message was,  
'stats data.frame must contain columns named 'pval', 'logFC', and 'expr''. 

I read the code in R folder and now I know that stats data.frame has to have a expr column, although I don't know what kind of values should be in that column. 

Could you describe what kind of values should be in?

Thank you in advance.

**Comment by suanzaoren** [comment]
> Hello,
> 
> I'm thrilled to apply BulkSignalR package to my reseach. While I was trying 'differential mode' example in manual (http://127.0.0.1:20402/library/BulkSignalR/doc/BulkSignalR-Differential.html),
> 
> I got an error in function 'defineClusterComp', and the error message was, 'stats data.frame must contain columns named 'pval', 'logFC', and 'expr''.
> 
> I read the code in R folder and now I know that stats data.frame has to have a expr column, although I don't know what kind of values should be in that column.
> 
> Could you describe what kind of values should be in?
> 
> Thank you in advance.

I also have the same doubt. May I ask if you have found the answer? If there is an answer, please let me know. Thanks

**Comment by jcolinge** [comment]
Sure. The motivation behind the so-called differential mode is to search for LRIs that are significantly regulated in one cluster of samples compared to another cluster or all the other samples. Accordingly, the user must provide a differential gene expression analysis table corresponding to the very comparison he or she wants to make. The stat.data.frame you refer to is just this table and the pval, logFC and expr columns must report for each gene the P-value of differential expression, the log-fold-change between the chosen cluster and the samples you compare it to, and the expression level in the chosen cluster, respectively. If you work with bulk data, you may for instance want to use edgeR or DESeq2 for the differential analysis.

Hope it is clearer like this.

Thanks for your interest in our package.
Jacques
